## -*- encoding: utf-8 -*-
## This file (Homework08.sagetex.sage) was *autogenerated* from Homework08.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Homework08', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
