## -*- encoding: utf-8 -*-
## This file (Homework03.sagetex.sage) was *autogenerated* from Homework03.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Homework03', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
